### ISSUE TITLE
Lowercase property names for action

### ISSUE THREAD

**Issue by patrick-stephens** [calyptia/fluent-linter-action#85]
Most actions seem to use lowercase properties for their configuration. Can we support either?

```
      - uses: calyptia/fluent-linter-action@main
        with:
          CALYPTIA_API_KEY: ...
          calyptia_api_key: ...
```

Not sure if we should use hyphens as well:

```
      - uses: calyptia/fluent-linter-action@main
        with:
          calyptia-api-key: ...
```
